language: clojure

lein: 
   - lein1
   - lein2
script: lein2 test :all
jdk:
  - openjdk7
 # - openjdk6
 # - oraclejdk7

matrix:
 exclude:
  - lein: lein1
 allow_failures:
  - lein: lein2

notifications:
  email: false
